name: DevOps Daily CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/devops-daily:latest

    - name: Restart Container on Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          docker stop devops-daily || true
          docker rm devops-daily || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/devops-daily:latest
          docker run -d -p 80:80 --name devops-daily ${{ secrets.DOCKER_USERNAME }}/devops-daily:latest
        EOF
