name: CI/CD - Build, Test, Push Docker & Deploy to Render

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2 — Setup QEMU
      - name: Set up QEMU (required for buildx)
        uses: docker/setup-qemu-action@v2

      # Step 3 — Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4 — Login to Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5 — Build & Push Docker image
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-daily:latest

      # Step 6 — Test container
      - name: Run container to test
        run: |
          docker run -d --name devops-daily-test -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/devops-daily:latest
          sleep 5
          curl -sSf http://localhost:8080 || (docker logs devops-daily-test && exit 1)
        shell: bash

      # Step 7 — Stop container
      - name: Stop test container
        if: always()
        run: docker rm -f devops-daily-test || true

      # Step 8 — Trigger Render deploy
      - name: Deploy to Render
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          https://api.render.com/deploy/srv-XXXXXXX
